### ISSUE TITLE
Containerize the query interface

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#111]
As a sys-admin, I can create a Docker container of the query interface environment that then exposes a web port, so that I can run the interface locally without doing a local installation of the environment.

Criteria:

- [x] There is a Dockerfile in the query repo that I can `docker build` to create a running Docker container of the query interface
- [x] When I run `docker build` on the Dockerfile in a fresh clone of the repository, my Docker container has all database migrations correctly applied, and I can open my local browser to see and use the query web interface
- [x] The containerized query interface can successfully send a query to a remote host (i.e. our Compute Canada instance) and will process a response

Resources:
- https://docs.docker.com/samples/django/

**Comment by jarmoza** [comment]
This is closed by #114
