### ISSUE TITLE
Pushing Docker image to Docker hub

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/concept_query#113]
Once the Dockerfile is in our repo and builds a local Docker image, let's

- [x] Push the image to Dockerhub
- [x] Write documentation for users of the repo to use `docker pull` the image instead of having to build it from the Dockerfile
- [x] In building this image, ensure that versions of base image, python, and required packages are locked in for consistent behavior

**Comment by surchs** [comment]
@jarmoza: This issue is completed, right? Do you have a link to the Dockerhub image of the concept query?

**Comment by jarmoza** [comment]
Yes, this issue is complete. The image can be found at https://hub.docker.com/repository/docker/jonathangrams/czi_demo_queryinterface

**Comment by surchs** [comment]
@jarmoza: you can add your Docs to this GDrive draft: https://docs.google.com/document/d/18z4IkwNcEd9V4KNDUvsuBtsWI_lWO8sVJL51EDKXJi8/edit?usp=sharing

**Comment by jarmoza** [comment]
@surchs Thank you!
