### ISSUE TITLE
Tag the current concept query version

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#118]
We now have a working dockerized version of the concept query app (https://github.com/neurobagel/concept_query/issues/113), we can start updating it to work with the new data model (https://github.com/neurobagel/concept_query/issues/95). But before we do that, we should tag the currently working Docker image and push it to a registry (e.g. Dockerhub), so that we can always get it back later if we want to show the old demo again.

**Comment by jarmoza** [comment]
Yes, this is closed. The current version of the query interface demo is tagged as `czi_demo`. It can be found [here](https://hub.docker.com/repository/docker/jonathangrams/query_interface) under my account currently. As we discussed, in the future we may want to list this image in a Neurobagel-specific dockerhub account.
