### ISSUE TITLE
add generated files to .gitignore

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#48]
We have a lot of files that are automatically generated and that change frequently. e.g.:

- `sqlite` file
- migrations from django
- the `query_choices.py` file

All of these can be re-generated from the "written" code. We should therefore ignore them and remove them from the git repo

**Comment by jarmoza** [comment]
Is this outdated?

I believe we decided that for the:
-[] sqlite file, we would commit a blank sqlite database file
-[] migrations, we would exclude them

As for the query_choices.py file, see #31 .

@surchs This may be closable.

**Comment by surchs** [comment]
I don't think we should close this yet. #59 is still open, and it's not clear to me that excluding migrations from the VSC is a good solution, the [docs seem to suggest the opposite](https://docs.djangoproject.com/en/3.2/topics/migrations/). I think we should first find some trustworthy source for best practices and then go with that.

**Comment by jarmoza** [comment]
Okay. I'll look into that as well as part of smaller tasks for next week.

**Comment by surchs** [comment]
I think we can close this
