### ISSUE TITLE
Dynamic styling implementation

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/concept_query#74]
There needs to be a solution for dynamically styling fields/values from the database.

One example of where this needs to occur is the image modalities that are being shown via badges in the query result cards.  The current implementation hardcodes potential modalities and their styles.

The beginning of this implementation exists in the uncommitted `query_styles.py`

See also #96

**Comment by surchs** [comment]
@jarmoza: what's the status of this issue? Has this been addressed?

**Comment by jarmoza** [comment]
@surchs This has not been addressed and is specific to the Python/Django implementation of the Concept Query tool. Given that the plan for the tool is to move it to Vue, it can be closed. (_But_ if we intend to modify the tool as is - which I'm pretty sure we do not - it's a reasonable task to keep open.)

**Comment by surchs** [comment]
Aha, thanks. That's very helpful. Yeah, we had planned to move from Django to Vue + API. So I think we can close this and similar issues safely now.
