### ISSUE TITLE
Think about switching to Django REST framework + Vue/React

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#96]

**Comment by jarmoza** [comment]
Just to note - the thinking on this has tilted toward VueJS this week as it may be easier to incorporate NIDM's ingestion tool.

**Comment by surchs** [comment]
We have adopted Vue for the annotation tool and it makes sense for us to use the same stack across apps. I think we have also decided to go with Vue for a revision of the Query tool. Closing this.
