### ISSUE TITLE
Run tests via makefile

### ISSUE THREAD

**Issue by surchs** [neurobagel/concept_query#99]
We should take a look at what [requests](https://github.com/psf/requests) is doing for their setup. They are using a single Makefile to run tests, coverage, and anything else we could come up with in the future. [Here is their Makefile](https://github.com/psf/requests/blob/main/Makefile). This would make it easier also for us to remember how to run our tools.

Done when:

- [ ] there is a makefile in the repository
- [ ] the makefile has a named workflow to run only the functional tests
- [ ] the make file has a named workflow to run (fast?) unit tests
- [ ] there is a named workflow to run both unit and functional tests

**Comment by jarmoza** [comment]
Agreed. This makes sense.
